# Generated by Django 3.0.7 on 2020-08-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motabasec',
            name='date',
            field=models.DateField(blank=1, null=1),
        ),
    ]
