# Generated by Django 3.0.7 on 2020-09-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200901_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motabamoy',
            name='date',
            field=models.DateField(blank=1, null=1),
        ),
    ]
