# Generated by Django 3.0.7 on 2020-09-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200901_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediasecparnt',
            name='withdegraycomp',
        ),
        migrations.AddField(
            model_name='mediasecparnt',
            name='withdegrey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Degrey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediasecparnt',
            name='withsecondray',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Secondary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='date',
            field=models.DateField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberesteda',
            field=models.PositiveIntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberhodor',
            field=models.PositiveIntegerField(blank=1, null=1),
        ),
    ]
