# Generated by Django 3.0.7 on 2020-09-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200901_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamoyparnt',
            name='withdegry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.DegreyMoyenCompany'),
        ),
    ]
