# Generated by Django 3.0.7 on 2020-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200902_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamoyparnt',
            name='date',
            field=models.DateTimeField(blank=1, null=1),
        ),
    ]
