# Generated by Django 3.0.7 on 2020-09-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200903_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamoyparnt',
            name='date',
            field=models.DateField(blank=1, null=1),
        ),
    ]
