# Generated by Django 3.0.7 on 2020-09-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200903_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamoyparnt',
            name='nomberesteda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediamoyparnt',
            name='nomberhodor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
