# Generated by Django 3.0.7 on 2020-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200903_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberesteda',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberhodor',
            field=models.PositiveIntegerField(),
        ),
    ]
