# Generated by Django 3.0.7 on 2020-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200903_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapreparnt',
            name='date',
            field=models.DateField(),
        ),
    ]
