# Generated by Django 3.0.7 on 2020-09-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200903_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapreparnt',
            name='withdegry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.DegreyPremCompany'),
        ),
    ]
