# Generated by Django 3.0.7 on 2020-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200904_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitename',
            name='typee',
            field=models.CharField(choices=[('1', 'ثانوي'), ('2', 'متوسط'), ('3', 'ابتدائي'), ('4', 'عام')], default='1', max_length=20),
        ),
    ]
