# Generated by Django 3.0.7 on 2020-09-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_activitename_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheractiv',
            name='withuser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
