# Generated by Django 3.0.7 on 2020-09-07 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_typefilemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemediamoy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TypeFileMedia'),
        ),
        migrations.AlterField(
            model_name='filemediasec',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.TypeFileMedia'),
        ),
        migrations.AlterField(
            model_name='typefilemedia',
            name='typee',
            field=models.IntegerField(),
        ),
    ]
