# Generated by Django 3.0.7 on 2020-09-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200907_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typefilemedia',
            name='typee',
        ),
    ]
