# Generated by Django 3.0.7 on 2020-09-08 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_remove_typefilemedia_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemediamoy',
            name='withdegry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.DegreyMoyenCompany'),
        ),
    ]
