# Generated by Django 3.0.7 on 2020-09-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20200919_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamoy',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mediapre',
            name='date',
            field=models.DateField(),
        ),
    ]
