# Generated by Django 3.0.7 on 2020-09-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200921_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directingmoy',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='directingsec',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='followcommit',
            name='date',
            field=models.DateField(blank=1, null=1),
        ),
    ]
