# Generated by Django 3.0.7 on 2020-09-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200925_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motabapre',
            name='withcompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Primary'),
        ),
    ]
