# Generated by Django 3.0.7 on 2020-10-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200930_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostachar',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mostachar',
            name='companystate1',
        ),
        migrations.RemoveField(
            model_name='mostachar',
            name='companystate2',
        ),
        migrations.RemoveField(
            model_name='mostachar',
            name='companystate3',
        ),
        migrations.AddField(
            model_name='mostachar',
            name='as1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='as2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='chhada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='clee',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='companystay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='dateactive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='datechhada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='datestart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='degry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='firstdatecomp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='lastdegry',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='nbrith',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='ncountccp',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='nomberchild',
            field=models.PositiveSmallIntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mostachar',
            name='placebrith',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='datenes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='firstdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='firstdateinsector',
            field=models.DateField(blank=True, null=True),
        ),
    ]
