# Generated by Django 3.0.7 on 2020-10-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20201012_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostachar',
            name='clee',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='lastdegry',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='nbrith',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='ncountccp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mostachar',
            name='nomberchild',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
