# Generated by Django 3.0.7 on 2020-10-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20201012_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreycompany',
            name='withdegreycomp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.MediaSecParnt'),
        ),
    ]
