# Generated by Django 3.0.7 on 2020-10-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_remove_degreycompany_withdegreycomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberesteda',
            field=models.IntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberhodor',
            field=models.IntegerField(blank=1, null=1),
        ),
    ]
