# Generated by Django 3.0.7 on 2020-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_auto_20201023_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberesteda',
            field=models.PositiveIntegerField(blank=1, null=1),
        ),
        migrations.AlterField(
            model_name='mediasecparnt',
            name='nomberhodor',
            field=models.PositiveIntegerField(blank=1, null=1),
        ),
    ]
